### ISSUE TITLE
Certain country codes do not convert to country names

### ISSUE THREAD

**Issue by ismailuddin** [mrmarkfrench/country-select-js#41] opened 2017-03-12 23:41 UTC
The function `$("#country").countrySelect("selectCountry", "gb");` does not work appropriately for all countries. For example, `gb`, `cy`, `ca` work fine, but `cz`, `ec` do not for some reason....? 

I should not the code forms part of a Laravel application, where the country code value is set in a separate hidden input field, and a JQuery script is used to set the country in the country selector. So only with certain countries does it set the name appropriately, but not with others...

**Comment by mrmarkfrench** [comment] 2019-02-22 05:19
Is this issue now resolved? I am unable to reproduce with the current version of the plugin, having tried with both of the examples you provided.

I'm going to close this issue, but if you still experience the problem, please let me know which countries you see it with, along with the version of jQuery you're using.

**Closed by mrmarkfrench** 2019-02-22 05:19 UTC
Labels: bug
